defaults:
  - default
  - _self_

# checkpoint
checkpoint_path: '/global/scratch/users/yifeizhou/20q/twenty_questions_gpt2_model0_full.pt'
save_path: '/global/scratch/users/yifeizhou/20q/archer_20q_15'

# env
env_name: twenty_questions
env_load_path: '/global/scratch/users/yifeizhou/20q/20q_t5_oracle.pt'

# wandb logging
use_wandb: True
project_name: 'llm_rl_20qsubset'
run_name: 'archer-acc'