defaults:
  - default
  - _self_

# checkpoint
checkpoint_path: null
save_path: '/home/yifei/llm_rl/20q/20q/archer_llm_20q_1'

# env
env_name: twenty_questions
env_load_path: '/home/yifei/llm_rl/LLM_RL/20q_t5_oracle.pt'

# model
agent_type: 'archer_llm'
policy_lm : 'mistralai/Mistral-7B-Instruct-v0.2'
max_new_tokens: 64
use_lora: True

# wandb logging
use_wandb: True
project_name: 'llm_rl_20qsubset'
run_name: 'archer-acc-llm-1e-7'