# Adversarial Attack Config
defaults:
  - default
  - _self_

# checkpoint
checkpoint_path: '/nfs/kun2/users/yifei/llm_rl/gpt2_bc_detective.pt'
save_path: '/nfs/kun2/users/yifei/llm_rl/dqn_adventure_1'

# env
env_name: adventure
env_load_path: '/nfs/kun2/users/yifei/llm_rl/ArCHer/dataset/detective.z5'

# wandb logging
use_wandb: False
project_name: 'llm_rl_20q'
run_name: 'archer-acc'