# Adversarial Attack Config
defaults:
  - default
  - _self_

env_load_path: '/nfs/kun2/users/yifei/llm_rl/city_t5_oracle.pt'
checkpoint_path: '/nfs/kun2/users/yifei/llm_rl/gpt2_bc_city.pt'
save_path: '/nfs/kun2/users/yifei/llm_rl/city_20q_1'

# env
env_name: guess_my_city

# wandb logging
use_wandb: False
project_name: 'llm_rl_city'
run_name: 'archer-acc'