compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
num_processes: 4
deepspeed_config:
  deepspeed_config_file: scripts/config/accelerate_config/ds_config.json
machine_rank: 0
main_training_function: main
num_machines: 1
use_cpu: false